import { FormEvent, useEffect, useState } from 'react'
import { Link, NavLink, Route, Routes } from 'react-router-dom'
import justiceImage from './assets/lady-justice.png'

type ButtonProps = { children: React.ReactNode; variant?: 'primary' | 'secondary' | 'text'; type?: 'button' | 'submit'; className?: string; loading?: boolean }
function Button({ children, variant = 'primary', type = 'button', className = '', loading = false }: ButtonProps) {
  return <button type={type} disabled={loading} className={`button button--${variant} ${className}`}>{loading ? <><span className="loader" aria-hidden="true" />Please wait</> : children}</button>
}

function Mark() { return <span className="mark" aria-hidden="true"><i /><i /><i /></span> }

function Navbar() {
  const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false)
  useEffect(() => { const update = () => setScrolled(window.scrollY > 16); update(); window.addEventListener('scroll', update, { passive: true }); return () => window.removeEventListener('scroll', update) }, [])
  return <header className={`navbar ${scrolled ? 'navbar--scrolled' : ''}`}><Link className="brand" to="/" onClick={() => setOpen(false)}><Mark />LEGALITE</Link>
    <button className="menu-toggle" aria-label="Toggle menu" aria-expanded={open} onClick={() => setOpen(!open)}><span /><span /></button>
    <nav className={open ? 'nav-links nav-links--open' : 'nav-links'} aria-label="Main navigation">
      <NavLink to="/">Home</NavLink><a href="/#how-it-works">How It Works</a><a href="/#support">Find Legal Help</a><a href="/#about">About</a>
      <span className="nav-spacer" /><Link className="login-link" to="/login">Login</Link><Link className="nav-cta" to="/register">Get Started <span>↗</span></Link>
    </nav>
  </header>
}

const values = [['01','Equality','Every person deserves a clear path to legal support.'],['02','Trust','Verified connections built around professional care.'],['03','Privacy','Your information is yours, protected by default.'],['04','Clarity','Every access decision is visible and understandable.']]
function Home() { return <><Navbar /><main>
  <section className="hero"><div className="hero-copy"><p className="eyebrow hero-enter hero-enter--1">LEGALITE · EQUAL ACCESS. SECURE JUSTICE.</p><h1 className="hero-enter hero-enter--2">Justice, <em>within reach.</em></h1><p className="hero-text hero-enter hero-enter--3">LEGALITE connects you with trusted legal assistance, securely and transparently — so the next step feels clear.</p><div className="actions hero-enter hero-enter--4"><Link className="button button--primary" to="/register">Find Legal Help <span>→</span></Link><Link className="button button--secondary" to="/register">Get Started</Link></div><p className="quiet-note hero-enter hero-enter--5"><span>✦</span> Private by design. Clear by default.</p></div>
  <div className="hero-art" aria-hidden="true"><div className="art-halo" /><img src={justiceImage} alt="" /></div><p className="hero-caption">A fairer path begins with access.</p></section>
  <section id="about" className="intro section"><p className="eyebrow">WHY LEGALITE</p><div><h2>Legal support should feel <em>human.</em></h2><p>We make it easier to understand your options, connect with verified providers and stay in control of the sensitive information that matters most.</p></div></section>
  <section id="how-it-works" className="section process"><div className="section-head"><p className="eyebrow">HOW IT WORKS</p><h2>A clear path forward.</h2></div><div className="steps">{[['01','Describe your legal need'],['02','Find verified providers'],['03','Connect securely'],['04','Manage access with consent']].map(([num, label]) => <article key={num}><span>{num}</span><h3>{label}</h3><p>{num === '01' ? 'Share only what is necessary, in your own words.' : num === '02' ? 'Explore suitable legal help with confidence.' : num === '03' ? 'Start a protected conversation when you are ready.' : 'See and control who can view your information.'}</p></article>)}</div></section>
  <section className="values section"><div className="value-copy"><p className="eyebrow">OUR PRINCIPLES</p><h2>Built for a more <em>equal</em> legal experience.</h2></div><div className="value-list">{values.map(([num,title,body]) => <article key={num}><span>{num}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></section>
  <section id="support" className="section control"><div><p className="eyebrow">YOUR INFORMATION, YOUR CONTROL</p><h2>Security you can see.</h2><p>Share sensitive documents with confidence. LEGALITE gives you a transparent history of access — and the power to revoke it at any time.</p><a className="arrow-link" href="#footer">Learn about document control <span>→</span></a></div><aside><p className="mini-label">ACCESS ACTIVITY</p><div className="access-row"><span className="avatar">AR</span><div><b>Access requested</b><small>Identity document · Today, 10:42</small></div><i>Review</i></div><div className="access-row"><span className="avatar avatar--dark">LS</span><div><b>Access granted</b><small>Case summary · Yesterday</small></div><i className="granted">Active</i></div><p className="activity-footer">All sharing requires your consent <span>↗</span></p></aside></section>
  <section className="final-cta"><div><p className="eyebrow">BEGIN WITH CONFIDENCE</p><h2>The first step toward trusted legal support.</h2><Link className="button button--primary" to="/register">Find Legal Help <span>→</span></Link><Link className="button button--secondary" to="/register">Create an Account</Link></div></section>
 </main><Footer /></> }

function Footer(){ return <footer id="footer"><Link className="brand" to="/"><Mark />LEGALITE</Link><p>Equal Access. Secure Justice.</p><small>© 2026 LEGALITE. Designed for fairer access.</small></footer> }

function AuthPage({ register = false }: { register?: boolean }) {
 const [submitted,setSubmitted] = useState(false); const [loading,setLoading] = useState(false); const [showPass,setShowPass] = useState(false); const [error,setError] = useState(''); const [password,setPassword] = useState('')
 const strength = password.length < 8 ? 'Use at least 8 characters' : /(?=.*[a-z])(?=.*[A-Z])(?=.*\d)/.test(password) ? 'Strong password' : 'Add upper-case letters and a number'
 const submit = (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const form = new FormData(e.currentTarget); const email = String(form.get('email') ?? ''); const pass = String(form.get('password') ?? ''); const confirm = String(form.get('confirmPassword') ?? ''); if (!/^\S+@\S+\.\S+$/.test(email)) return setError('Enter a valid email address.'); if (pass.length < 8) return setError('Your password must contain at least 8 characters.'); if (register && pass !== confirm) return setError('Your passwords do not match.'); setError(''); setLoading(true); window.setTimeout(() => { setLoading(false); setSubmitted(true) }, 550) }
 return <div className="auth"><Navbar /><main className="auth-main"><section className="auth-art" aria-hidden="true"><img src={justiceImage} alt="" /><p>Equal access begins with a clear first step.</p></section><section className="auth-form"><Link className="back" to="/">← Back to home</Link><p className="eyebrow">{register ? 'CREATE YOUR ACCOUNT' : 'SECURE ACCESS'}</p><h1>{register ? <>Create your LEGALITE <em>Account.</em></> : <>Welcome <em>Back.</em></>}</h1><p>{register ? 'Access trusted legal support with security, privacy and control.' : 'Sign in securely to continue to LEGALITE.'}</p>
 <form onSubmit={submit} noValidate aria-describedby={error ? 'form-error' : undefined}>{register && <><label>Full name<input required name="fullName" autoComplete="name" placeholder="Your full name" /></label><label>How will you use LEGALITE?<select defaultValue="citizen"><option value="citizen">Citizen seeking legal support</option><option value="provider">Legal service provider</option></select></label></>}<label>Email address<input required type="email" name="email" autoComplete="email" placeholder="you@example.com" aria-invalid={error.includes('email')} /></label>{register && <label>Phone number <small>(optional)</small><input type="tel" name="phone" autoComplete="tel" placeholder="Your phone number" /></label>}<label>Password<div className="password"><input required minLength={8} type={showPass ? 'text':'password'} name="password" onChange={e => setPassword(e.target.value)} autoComplete={register ? 'new-password':'current-password'} placeholder="Enter your password" aria-invalid={error.includes('password')} /><button type="button" aria-label={showPass ? 'Hide password' : 'Show password'} onClick={() => setShowPass(!showPass)}>{showPass ? 'Hide':'Show'}</button></div></label>{register && <p className={`password-strength ${password.length >= 8 ? 'password-strength--ready' : ''}`}>{strength}</p>}{register && <label>Confirm password<div className="password"><input required minLength={8} type={showPass ? 'text':'password'} name="confirmPassword" autoComplete="new-password" placeholder="Confirm your password" aria-invalid={error.includes('match')} /></div></label>}{!register && <div className="form-row"><label className="check"><input type="checkbox" /> <span>Remember this device</span></label><a href="#reset">Forgot password?</a></div>}{register && <label className="check consent"><input required type="checkbox" /> <span>I agree to the Terms of Use and acknowledge the Privacy Notice.</span></label>}<Button type="submit" loading={loading} className="form-button">{register ? 'Create Account':'Sign In'} <span>→</span></Button>{error && <p id="form-error" className="form-error" role="alert">{error}</p>}{submitted && <p className="form-message" role="status">This frontend is ready for a secure server connection. Your details have not been sent.</p>}</form><p className="auth-switch">{register ? 'Already have an account?' : "Don't have an account?"} <Link to={register ? '/login':'/register'}>{register ? 'Sign in':'Create an account'}</Link></p></section></main></div>
}

export default function App(){ return <Routes><Route path="/" element={<Home />} /><Route path="/login" element={<AuthPage />} /><Route path="/register" element={<AuthPage register />} /><Route path="*" element={<Home />} /></Routes> }
